### ISSUE TITLE
Romanisation du 10

### ISSUE THREAD

**Issue by sCreami** [ukonline/PolyGlot#1]
Dans le chapitre sur compter de 1 à 10 :

> 10     十 じゅう \romaji{j\=u}

"jyū" ne serait pas une romanisation plus appropriée ?

**Comment by combefis** [comment]
Oui, on a longtemps réfléchi sur cela, et pour finir on est parti sur la _romanisation HepBurn_ qui est sans conteste la plus répandue et précise pour les personnes provenant des langues latines. C'est d'ailleurs également cette dernière qui est utilisée par Google Translate.

https://www.wikiwand.com/en/Hepburn_romanization

**Comment by sCreami** [comment]
Il serait bien de préciser quel choix de romanisation a été sélectionné dans le texte dans ce cas.

**Comment by combefis** [comment]
Excellente suggestion! Une page README spécifique pour le japonais a été ajoutée, mentionnant le choix du système de romanisation.
